name: smart_class_check_in_learning_reflection_app
description: MVP Flutter app for smart class check-in and learning reflection.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.6.5
  cloud_functions: ^5.3.4
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  geolocator: ^13.0.2
  mobile_scanner: ^6.0.2
  path: ^1.9.0
  sqflite: ^2.4.1
  sqflite_common_ffi_web: ^1.0.1+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sqlite/sqflite_sw.js
    - assets/sqlite/sqlite3.wasm
