// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOKa2HH_DN5lNhAWbinTYda7MJvg00gg0',
    appId: '1:554746987894:web:3a18d5e3a2c200b6c7a657',
    messagingSenderId: '554746987894',
    projectId: 'smart-class-check-in-n-l-r-app',
    authDomain: 'smart-class-check-in-n-l-r-app.firebaseapp.com',
    storageBucket: 'smart-class-check-in-n-l-r-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOU4DGrJytmCTGJAzH9wu5DisUe95TjvY',
    appId: '1:554746987894:android:3da6bb80cd7d2d4dc7a657',
    messagingSenderId: '554746987894',
    projectId: 'smart-class-check-in-n-l-r-app',
    storageBucket: 'smart-class-check-in-n-l-r-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC91fFgWbNBKg3Umnn9yB7zKwzig-zwmBY',
    appId: '1:554746987894:ios:7f5db6de1dd4e13dc7a657',
    messagingSenderId: '554746987894',
    projectId: 'smart-class-check-in-n-l-r-app',
    storageBucket: 'smart-class-check-in-n-l-r-app.firebasestorage.app',
    iosBundleId: 'com.example.smartClassCheckInLearningReflectionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC91fFgWbNBKg3Umnn9yB7zKwzig-zwmBY',
    appId: '1:554746987894:ios:7f5db6de1dd4e13dc7a657',
    messagingSenderId: '554746987894',
    projectId: 'smart-class-check-in-n-l-r-app',
    storageBucket: 'smart-class-check-in-n-l-r-app.firebasestorage.app',
    iosBundleId: 'com.example.smartClassCheckInLearningReflectionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOKa2HH_DN5lNhAWbinTYda7MJvg00gg0',
    appId: '1:554746987894:web:200312302a67a882c7a657',
    messagingSenderId: '554746987894',
    projectId: 'smart-class-check-in-n-l-r-app',
    authDomain: 'smart-class-check-in-n-l-r-app.firebaseapp.com',
    storageBucket: 'smart-class-check-in-n-l-r-app.firebasestorage.app',
  );
}